### ISSUE TITLE
(IMPORT FAILED): C:\Users\kim\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IDM-VTON

### ISSUE THREAD

**Issue by wonderbird2** [TemryL/ComfyUI-IDM-VTON#14] opened 2024-05-05 20:48 UTC
Allocation on device 0 would exceed allowed memory. (out of memory)

why? help me.. plz..
![ComfyUI](https://github.com/TemryL/ComfyUI-IDM-VTON/assets/168997745/f223fff5-32b4-43ad-96aa-2ffa2dac4b26)

**Comment by TemryL** [comment] 2024-05-07 19:41
Hi, thanks for your issue report. It looks like it is a duplicate of [this issue](https://github.com/TemryL/ComfyUI-IDM-VTON/issues/4). I will close this one.

**Closed by TemryL** 2024-05-07 19:41 UTC
